version: "3"

services:
  jekyll:
    image: "jekyll/jekyll:4.2.2"
    platform: "linux/amd64"
    volumes: [".:/srv/jekyll:Z"]
    ports: ["4000:4000"]
    command: ["jekyll", "serve", "-s", "docs"]
