name: Update openapi.json
on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"

jobs:
  update:
    # if: false # disable until further notice
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.AIRFOCUSBOT_GITHUB_TOKEN }}
      - name: Update openapi.json
        run: |
          git config --global user.email "christian+airfocusbot@airfocus.io"
          git config --global user.name "airfocusbot"
          bash .github/actions/update.sh --push
